; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; [env:yolo_uno]
; platform = espressif32
; board = yolo_uno
; framework = arduino
; monitor_speed = 115200
; board_build.filesystem = littlefs

; lib_deps =
;     tanakamasayuki/TensorFlowLite_ESP32@1.0.0
;     adafruit/Adafruit NeoPixel@^1.15.1
;     DHT20
;     LCD
;     PubSubClient
;     mikalhart/TinyGPSPlus@^1.1.0
;     plerup/EspSoftwareSerial@^8.2.0
;     WiFi
;     ; me-no-dev/AsyncTCP@^3.4.9
;     https://github.com/me-no-dev/ESPAsyncWebServer.git

;     ; https://github.com/me-no-dev/ESPAsyncWebServer.git#3.6.0
;     ElegantOTA
; lib_ignore = ESPAsyncTCP, RPAsyncTCP
; lib_compat_mode = strict

; build_flags =
;     -D ARDUINO_USB_MODE=1
;     -D ARDUINO_USB_CDC_ON_BOOT=1
;     -DSSID_AP='"ESP32 setup"'
;     -DPASS_AP='12345678'
;     -DELEGANTOTA_USE_ASYNC_WEBSERVER=1


[env:esp32-c3-relay]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs



lib_deps =
    ; tanakamasayuki/TensorFlowLite_ESP32@1.0.0
    DHT20
    ; LCD
    PubSubClient
    mikalhart/TinyGPSPlus@^1.1.0
    plerup/EspSoftwareSerial@^8.2.0
    WiFi
    ; me-no-dev/AsyncTCP@^3.4.9
    https://github.com/me-no-dev/ESPAsyncWebServer.git

    ; ESPAsyncWebServer mới tương thích core v3
    ; https://github.com/me-no-dev/ESPAsyncWebServer.git#3.6.0
    ElegantOTA
lib_ignore = ESPAsyncTCP, RPAsyncTCP
lib_compat_mode = strict

build_flags =
    -D TFLITE_ESP32_DISABLE_SCREEN=1
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -DSSID_AP='"ESP32 setup"'
    -DPASS_AP='12345678'
    -DELEGANTOTA_USE_ASYNC_WEBSERVER=1
